2021-02-09 12:10:24.882 UTC [1158] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-02-09 12:10:24.885 UTC [1158] LOG:  listening on Unix socket "/home/solanav/krptkn/.s.PGSQL.5432"
2021-02-09 12:10:24.900 UTC [1159] LOG:  database system was interrupted; last known up at 2021-02-09 10:58:39 UTC
2021-02-09 12:10:25.160 UTC [1159] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-09 12:10:25.162 UTC [1159] LOG:  redo starts at 0/23A48D8
2021-02-09 12:10:25.165 UTC [1159] LOG:  invalid record length at 0/23B9F90: wanted 24, got 0
2021-02-09 12:10:25.165 UTC [1159] LOG:  redo done at 0/23B9F58
2021-02-09 12:10:25.165 UTC [1159] LOG:  last completed transaction was at log time 2021-02-09 11:00:39.536203+00
2021-02-09 12:10:25.194 UTC [1158] LOG:  database system is ready to accept connections
2021-02-09 12:10:25.277 UTC [1167] ERROR:  database "krptkn_dev" already exists
2021-02-09 12:10:25.277 UTC [1167] STATEMENT:  CREATE DATABASE krptkn_dev;
2021-02-09 13:06:09.926 UTC [877] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-02-09 13:06:09.930 UTC [877] LOG:  listening on Unix socket "/home/solanav/krptkn/.s.PGSQL.5432"
2021-02-09 13:06:09.949 UTC [878] LOG:  database system was interrupted; last known up at 2021-02-09 12:30:28 UTC
2021-02-09 13:06:10.208 UTC [878] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-09 13:06:10.211 UTC [878] LOG:  redo starts at 0/2404840
2021-02-09 13:06:10.227 UTC [878] LOG:  invalid record length at 0/24BB088: wanted 24, got 0
2021-02-09 13:06:10.227 UTC [878] LOG:  redo done at 0/24BB060
2021-02-09 13:06:10.227 UTC [878] LOG:  last completed transaction was at log time 2021-02-09 12:33:53.688354+00
2021-02-09 13:06:10.253 UTC [877] LOG:  database system is ready to accept connections
2021-02-09 13:06:10.329 UTC [886] ERROR:  database "krptkn_dev" already exists
2021-02-09 13:06:10.329 UTC [886] STATEMENT:  CREATE DATABASE krptkn_dev;
2021-02-09 13:41:20.730 UTC [877] LOG:  received fast shutdown request
2021-02-09 13:41:20.732 UTC [877] LOG:  aborting any active transactions
2021-02-09 13:41:20.733 UTC [877] LOG:  background worker "logical replication launcher" (PID 884) exited with exit code 1
2021-02-09 13:41:20.733 UTC [879] LOG:  shutting down
2021-02-09 13:41:20.746 UTC [877] LOG:  database system is shut down
2021-02-09 13:42:00.528 UTC [1717] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-02-09 13:42:00.532 UTC [1717] LOG:  listening on Unix socket "/home/solanav/krptkn/.s.PGSQL.5432"
2021-02-09 13:42:00.544 UTC [1718] LOG:  database system was shut down at 2021-02-09 13:41:20 UTC
2021-02-09 13:42:00.548 UTC [1717] LOG:  database system is ready to accept connections
2021-02-09 13:42:00.627 UTC [1726] ERROR:  database "krptkn_dev" already exists
2021-02-09 13:42:00.627 UTC [1726] STATEMENT:  CREATE DATABASE krptkn_dev;
2021-02-09 13:42:21.595 UTC [1717] LOG:  received fast shutdown request
2021-02-09 13:42:21.605 UTC [1717] LOG:  aborting any active transactions
2021-02-09 13:42:21.606 UTC [1717] LOG:  background worker "logical replication launcher" (PID 1724) exited with exit code 1
2021-02-09 13:42:21.606 UTC [1719] LOG:  shutting down
2021-02-09 13:42:21.625 UTC [1717] LOG:  database system is shut down
